from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup, ReplyKeyboardMarkup,KeyboardButton


BTN_CONDITIONS = InlineKeyboardButton('Условия проведения съемки❗️', callback_data='conditions')
BTN_PICTURES = InlineKeyboardButton('Примеры готовых работ📔', callback_data='pictures')
BTN_VARIANTS = InlineKeyboardButton('Варианты съемок📷', callback_data='variants')
BTN_EXPRESS = InlineKeyboardButton('Экспресс съмка⏱', callback_data='express')
BTN_CONTENT = InlineKeyboardButton('Контент съмка🚀', callback_data='content')
BTN_TFP = InlineKeyboardButton('TFP-съемка📰', callback_data='tfp')
BTN_FOOD = InlineKeyboardButton('Фуд-съемка🍇', callback_data='food')
BTN_INDIVIDUAL = InlineKeyboardButton('Индивидуальная съемка🧍🏼‍♂️', callback_data='individual')
BTN_LOVE = InlineKeyboardButton('Love-story💕', callback_data='love')
BTN_FAMILY = InlineKeyboardButton('Семейная съемка👨‍👩‍👧', callback_data='family')
BTN_WRT = InlineKeyboardButton('Записаться можно здесь\n ⬇️', callback_data='wrt')
BTN_PHOTO1 = InlineKeyboardButton('Пример работы', callback_data='photo1')
BTN_PHOTO2 = InlineKeyboardButton('Пример работы', callback_data='photo2')
BTN_PHOTO3 = InlineKeyboardButton('Пример работы', callback_data='photo3')
BTN_PHOTO4 = InlineKeyboardButton('Пример работы', callback_data='photo4')
BTN_PHOTO5 = InlineKeyboardButton('Пример работы', callback_data='photo5')
BTN_PHOTO6 = InlineKeyboardButton('Пример работы', callback_data='photo6')
BTN_PHOTO7 = InlineKeyboardButton('Пример работы', callback_data='photo7')

START = InlineKeyboardMarkup().add(BTN_CONDITIONS).add(BTN_VARIANTS).add(BTN_PICTURES)
CONDITIONS = InlineKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(BTN_VARIANTS).add(BTN_PICTURES)
PICTURES = InlineKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(BTN_VARIANTS).add(BTN_CONDITIONS)
VARIANTS = InlineKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).add(BTN_EXPRESS, BTN_CONTENT).add(BTN_TFP, BTN_FOOD).add(BTN_INDIVIDUAL, BTN_LOVE).add(BTN_FAMILY)
EXPRESS = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_WRT).add(BTN_PHOTO1)
CONTENT = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_WRT).add(BTN_PHOTO2)
TFP = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_WRT).add(BTN_PHOTO7)
FOOD = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_WRT).add(BTN_PHOTO4)
INDIVIDUAL = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_WRT).add(BTN_PHOTO5)
LOVE = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_WRT).add(BTN_PHOTO6)
FAMILY = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_WRT).add(BTN_PHOTO3)
WRT = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
PHOTO1 = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
PHOTO2 = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
PHOTO3 = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
PHOTO4 = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
PHOTO5 = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
PHOTO6 = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
PHOTO7 = InlineKeyboardMarkup().add(BTN_VARIANTS).add(BTN_CONDITIONS)
